name: Java CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: mephisto2005555/javaoffer
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Build production package with obfuscation and CSS minification
        run: mvn clean package -Pprod

      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE_NAME:${IMAGE_TAG} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push $DOCKER_IMAGE_NAME:${IMAGE_TAG}

      - name: Deploy to Windows Server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 2222
          script: powershell -Command "Set-Location 'C:/Users/Boom/Desktop/javaoffer'; 'IMAGE_TAG=${{ github.sha }}' | Out-File -Encoding ASCII .env; Get-Content .env; docker compose pull; docker compose up -d --force-recreate; docker compose ps; Write-Host 'Deployment completed!'"
