name: Java CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: mephisto2005555/javaoffer  # Docker Hub

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Build and test with Maven
        run: mvn clean test

      - name: Build production package with obfuscation and CSS minification
        run: mvn clean package -Pprod -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE_NAME:latest .

      - name: Push Docker image to Docker Hub
        run: docker push $DOCKER_IMAGE_NAME:latest

      - name: Deploy to Windows Server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd "C:/Users/Boom/Desktop/javaoffer"
            docker compose pull
            docker compose up -d